version: 2

references:
  container_config: &container_config
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.9.0
  add_workspace: &add_workspace
    attach_workspace:
      at: .

jobs:
  checkout:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - core-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
      - run:
          name: Check yarn version
          command: yarn --version
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: core-dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-packages:
    <<: *container_config
    steps:
      - *add_workspace
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - packages/**/dist
  lint:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: Run eslint
          command: yarn lint
      - run:
          name: Run flow type check
          command: yarn flow
  test:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: Run tests
          command: yarn test
  deploy-packages:
    <<: *container_config
    steps:
      - *add_workspace
      - run:
          name: Config git
          command: |
            touch ~/.gitconfig
            git config --global -l
            git config --global user.email development@gopato.com
            git config --global user.name GodPato
      - run:
          name: Add NPM token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/tmp/.npmrc
      - add_ssh_keys:
          fingerprints:
            - "07:d7:a9:a0:a1:c6:6d:dc:f1:6f:ea:fb:16:37:45:ff"
      - run:
          name: Update known_hosts
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - deploy:
          name: Release NPM packages
          command: yarn release -y

workflows:
  version: 2
  deploy:
    jobs:
      - checkout
      - build-packages:
          requires:
            - checkout
      - lint:
          requires:
            - build-packages
      - test:
          requires:
            - build-packages
      - approve-deploy:
          type: approval
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
      - deploy-packages:
          requires:
            - approve-deploy
          filters:
            branches:
              only: master
